{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[administration,index,login,mobile,nitrogen_app,
                        nitrogen_inets,nitrogen_sup,scenario,scenarios,
                        settings,stats,terminal,updates]}]}.
